apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: UIBK-backstage
  description: A  Testing Backstage application.
  links:
  - title: UIBK Website
    url: https://uibk.ac.at
  - title: Cloudnative Overview
    url: https://wiki.uibk.ac.at
  # Example for optional annotations
  annotations:
     github.com/project-slug: backstage/backstage
     backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: guest
  lifecycle: development
